#Automatically generated by RTLinux Makefile
RTL_DIR = /home/erts/Desktop/Spark Code/IITdelivery/spark_x86_version2/code/spark_demo/SParK/Spark

CFLAGS = -Wno-uninitialized -O2 -D__KERNEL__ -nostdinc -fno-builtin -I/home/erts/Desktop/Spark Code/IITdelivery/spark_x86_version2/code/spark_demo/SParK/Spark/include/dietlibc -I/home/erts/Desktop/Spark Code/IITdelivery/spark_x86_version2/code/spark_demo/SParK/Spark/include -fomit-frame-pointer
ARCH = i386
CC = gcc
BUILD_DIR = /home/erts/Desktop/Spark Code/IITdelivery/spark_x86_version2/code/spark_demo/SParK/Spark/build
OBJ_DIR = /home/erts/Desktop/Spark Code/IITdelivery/spark_x86_version2/code/spark_demo/SParK/Spark/build/objs
LIB_DIR = /home/erts/Desktop/Spark Code/IITdelivery/spark_x86_version2/code/spark_demo/SParK/Spark/build/libs
IMAGE_DIR = /home/erts/Desktop/Spark Code/IITdelivery/spark_x86_version2/code/spark_demo/SParK/Spark/build
