#Automatically generated by RTLinux Makefile
RTL_DIR = /home/erts/SPaRK_x86/Spark

CFLAGS = -Wno-uninitialized -O2 -D__KERNEL__ -nostdinc -fno-builtin -I/home/erts/SPaRK_x86/Spark/include/dietlibc -I/home/erts/SPaRK_x86/Spark/include -fomit-frame-pointer -fno-stack-protector
ARCH = i386
CC = gcc
BUILD_DIR = /home/erts/SPaRK_x86/Spark/build
OBJ_DIR = /home/erts/SPaRK_x86/Spark/build/objs
LIB_DIR = /home/erts/SPaRK_x86/Spark/build/libs
IMAGE_DIR = /home/erts/SPaRK_x86/Spark/build
