#Automatically generated by RTLinux Makefile
RTL_DIR = /root/surabhi/networkstack_dvpt/rollback/SParK/Spark

CFLAGS = -Wno-uninitialized -O2 -D__KERNEL__ -nostdinc -fno-builtin -I/root/surabhi/networkstack_dvpt/rollback/SParK/Spark/include/dietlibc -I/root/surabhi/networkstack_dvpt/rollback/SParK/Spark/include -fomit-frame-pointer
ARCH = i386
CC = gcc
BUILD_DIR = /root/surabhi/networkstack_dvpt/rollback/SParK/Spark/build
OBJ_DIR = /root/surabhi/networkstack_dvpt/rollback/SParK/Spark/build/objs
LIB_DIR = /root/surabhi/networkstack_dvpt/rollback/SParK/Spark/build/libs
IMAGE_DIR = /root/surabhi/networkstack_dvpt/rollback/SParK/Spark/build
