#Automatically generated by RTLinux Makefile
RTL_DIR = /root/surabhi/networkstack_dvpt/rollback/SParK/GuestOS2

CFLAGS = -Wno-uninitialized -O2 -D__KERNEL__ -nostdinc -fno-builtin -I/root/surabhi/networkstack_dvpt/rollback/SParK/GuestOS2/include/dietlibc -I/root/surabhi/networkstack_dvpt/rollback/SParK/GuestOS2/include -fomit-frame-pointer
ARCH = i386
CC = gcc
BUILD_DIR = /root/surabhi/networkstack_dvpt/rollback/SParK/GuestOS2/build
OBJ_DIR = /root/surabhi/networkstack_dvpt/rollback/SParK/GuestOS2/build/objs
LIB_DIR = /root/surabhi/networkstack_dvpt/rollback/SParK/GuestOS2/build/libs
IMAGE_DIR = /root/surabhi/networkstack_dvpt/rollback/SParK/GuestOS2/build
